# Generated by Django 2.2.1 on 2019-05-31 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('pages', models.IntegerField()),
                ('no_of_copies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('country', models.CharField(max_length=5, null=True)),
                ('profile_path', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BooksStudentsRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libapp.PublicationHouse'),
        ),
        migrations.AddField(
            model_name='book',
            name='students',
            field=models.ManyToManyField(through='libapp.BooksStudentsRel', to='libapp.Student'),
        ),
    ]
